const data = [
    {
        "id": 0,
        "title": "Betty, la fea",
        "Rating": "(5.0 rating)",
        "sinopsis": "Beatriz Pinzón Solano es una brillante economista con maestría en finanzas; solo tiene un defecto: es fea. Todo cambia cuando comienza a trabajar en Ecomoda, una de las empresas más grandes del país, donde conoce y se enamora del presidente Armando Mendoza.",
        "Clasificación": "+14",
        "banner": "archivos-html/banner-betty.jpeg",
        "Tarjeta": "recomendados/betty-poster.jpeg",
    },
    {
        "id": 1,
        "title": "Barbie",
        "Rating": "(4.0 rating)",
        "sinopsis": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        "Clasificación": "+12",
        "banner": "banners/banner-barbie.jpeg",
        "Tarjeta": "recomendados/barbie.jpeg",
    },
    {
        "id": 2,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 3,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 4,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 5,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 6,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 7,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 8,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "",
        "Tarjeta": "",
    }
]