const data = [
    {
        "id": 0,
        "title": "Betty, la fea",
        "Rating": "(3.8 rating)",
        "sinopsis": "Beatriz Pinzón Solano es una brillante economista con maestría en finanzas; solo tiene un defecto: es fea. Todo cambia cuando comienza a trabajar en Ecomoda, una de las empresas más grandes del país, donde conoce y se enamora del presidente Armando Mendoza.",
        "Clasificación": "+14",
        "banner": "archivos-html/banner-betty.jpeg",
        "Tarjeta": "recomendados/betty-poster.jpeg",
    },
    {
        "id": 1,
        "title": "Barbie",
        "Rating": "(4.0 rating)",
        "sinopsis": "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
        "Clasificación": "+12",
        "banner": "banners/banner-barbie.jpeg",
        "Tarjeta": "recomendados/barbie.jpeg",
    },
    {
        "id": 2,
        "title": "2001: Odisea del espacio",
        "Rating": "(5.0)",
        "sinopsis": "La historia de la humanidad, en diversos estadios del pasado y del futuro, es narrada en la película de ciencia-ficción de culto por excelencia de la historia del cine. Hace millones de años, en los albores del nacimiento del homo sapiens, unos simios descubren un monolito que les lleva a un estadio de inteligencia superior.",
        "Clasificación": "+14",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "recomendados/2001.jpeg",
    },
    {
        "id": 3,
        "title": "Breaking Bad",
        "Rating": "(5.0)",
        "sinopsis": "Tras cumplir 50 años, Walter White , un profesor de química de un instituto de Albuquerque, Nuevo México, se entera de que tiene un cáncer de pulmón incurable. Casado con Skyler  y con un hijo discapacitado , la brutal noticia lo impulsa a dar un drástico cambio a su vida: decide, con la ayuda de un antiguo alumno , fabricar anfetaminas y ponerlas a la venta.",
        "Clasificación": "+18",
        "banner": "banners/banner-breakingbad.jpeg",
        "Tarjeta": "recomendados/breakingbad.jpeg",
    },
    {
        "id": 4,
        "title": "Friends",
        "Rating": "(4.0)",
        "sinopsis": "Friends narra las aventuras y desventuras de seis jóvenes de Nueva York. Rachel, Monica, Phoebe, Ross, Chandler y Joey forman una unida pandilla de amigos que viven en Manhattan y que suelen reunirse en sus apartamentos o en su bar habitual, el Central Perk.",
        "Clasificación": "+14",
        "banner": "banners/banner-friends.jpeg",
        "Tarjeta": "recomendados/friends.jpeg",
    },
    {
        "id": 5,
        "title": "Como conocí a su madre",
        "Rating": "(3.8)",
        "sinopsis": "Un padre cuenta a sus hijos, a través de una serie de flashbacks, el viaje que él y sus cuatro mejores amigos hicieron antes de conocer a su madre.",
        "Clasificación": "+14",
        "banner": "banners/banner-himym.jpeg",
        "Tarjeta": "recomendados/himym.jpeg",
    },
    {
        "id": 6,
        "title": "Hora de aventura",
        "Rating": "(4.0)",
        "sinopsis": "¡No son justos, son injustos! Conéctate con Finn y Jake mientras viajan por la Tierra de Ooo en busca de aventuras. Pero recuerda, la aventura no siempre es fácil.",
        "Clasificación": "+10",
        "banner": "banners/banner-hora-de-aventura.jpeg.jpeg",
        "Tarjeta": "recomendados/hora-de-aventura.jpeg",
    },
    {
        "id": 7,
        "title": "Oppenheimer",
        "Rating": "(4.5)",
        "sinopsis": "La verdadera historia del recorrido del físico J. Robert Oppenheimer, de científico ambicioso y motivado a hombre atormentado y lleno de remordimientos, golpeado por la gravedad de lo que había hecho. Para Oppenheimer, la detonación con éxito de la primera bomba atómica valida años de incansable trabajo. Pero en este momento de aparente triunfo, Oppenheimer ve ante sí un poder destructivo de magnitud casi sobrenatural.",
        "Clasificación": "+16",
        "banner": "banners/banner-oppenheimer.jpeg",
        "Tarjeta": "recomendados/oppenheimer.jpeg",
    },
    {
        "id": 8,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    },
    {
        "id": 1,
        "title": "",
        "Rating": "()",
        "sinopsis": "",
        "Clasificación": "+1",
        "banner": "banners/banner-2001.jpeg",
        "Tarjeta": "originales/barbie.jpeg",
    }
]